[package]
name = "actix-governor"
version = "0.1.0"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2018"
description = "A rate limiter for actix-web based on the governor crate"
repository = "https://github.com/AaronErhardt/Triox"
readme = "README.md"
license = "GPL-3.0-or-later"

keywords = ["actix", "rate-limit", "governor"]
categories = ["web-programming::http-server"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0"
actix-service = "1.0"
futures = "0.3"
governor = "0.3"
log = "0.4"
